controller_manager:
  ros__parameters:
    update_rate: 250  # Hz

    explorer_custom_controller:
      type: explorer_command_controllers/CustomController

    qontrol_explorer:
      type: qontrol_controller/QontrolVelocityController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    sandbox_controller:
      type: sandbox/SandboxController

    gripper_controller:
      type: forward_command_controller/ForwardCommandController

qontrol_explorer:
  ros__parameters:
    # Base parameters
    robot_description_origin: robot_state_publisher
    tip_frame: tool0
    root_frame: base_link
    state_interface:
      - position
      - velocity
      - effort
  
    chainable_controller_name: explorer_custom_controller
    robot_command: qp_position
    reference_interface_name: velocity

    # Velocity parameters
    command_max_linear_velocity: 0.05
    command_max_angular_velocity: 1.0
    refresh_mapping: True
    open_loop: True
    input_topic_name: /explorer_user_interfaces/rqt_armcontrol/input_device_velocity
    regularisation_weight: 1e-2
    root_frame_control: True
    deadzone: 0.1
    velocity_limit: 0.5
    horizon: 15
    p_gain: 100.0
    lambda: 0.1
    points_collision: [0.0, -0.6, 0.0, 0.0, -0.6, 1.0]
    wall_constraint_horizon: 15
    d_secure: 0.2
    d_prevent: 0.2
    elbow_frame: "link_3"
    handle_frame: "link_5"

gripper_controller:
  ros__parameters:
    joints:
      - right_finger_joint
    interface_name: position

sandbox_controller:
  ros__parameters:
    robot_type: "explorer_velocity"
    tool_frame: "tool0"
    base_frame: "base_link"
    input_topic_name: "/teleop_cmd"
    command_names:
      - "qontrol_explorer/velocity/linear_x"
      - "qontrol_explorer/velocity/linear_y"
      - "qontrol_explorer/velocity/linear_z"
      - "qontrol_explorer/velocity/angular_x"
      - "qontrol_explorer/velocity/angular_y"
      - "qontrol_explorer/velocity/angular_z"

explorer_custom_controller:
  ros__parameters:
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
    settings:
      joint_1: { 
        mode: "position",
        command_interface_names: ["effort", "position", "velocity"],
        state_interface_names: ["effort", "position", "velocity"],
        impedance_damping: 1.0,
        impedance_stiffness: 2.0,
        enable_limits: false,
        position_command_min: -0.2,
        position_command_max:  0.2,
        position_step_max: 0.0005,
      }
      joint_2: {
        mode: "position",
        command_interface_names: ["effort", "position", "velocity"],
        state_interface_names: ["effort", "position", "velocity"],
        impedance_damping: 1.5,
        impedance_stiffness: 2.5,
        enable_limits: false,
        position_command_min: -1.57,
        position_command_max: -0.78,
        position_step_max: 0.0005,
      }
      joint_3: {
        mode: "position",
        command_interface_names: ["effort", "position", "velocity"],
        state_interface_names: ["effort", "position", "velocity"],
        impedance_damping: 1.0,
        impedance_stiffness: 2.0,
        enable_limits: false,
        position_command_min: -0.78,
        position_command_max:  0.78,
        position_step_max: 0.0005,
      }
      joint_4: {
        mode: "position",
        command_interface_names: ["effort", "position", "velocity"],
        state_interface_names: ["effort", "position", "velocity"],
        impedance_damping: 0.5,
        impedance_stiffness: 1.0,
        enable_limits: false,
        position_command_min: -1.0,
        position_command_max:  1.0,
        position_step_max: 0.2,
      }
      joint_5: {
        mode: "position",
        command_interface_names: ["effort", "position", "velocity"],
        state_interface_names: ["effort", "position", "velocity"],
        impedance_damping: 0.7,
        impedance_stiffness: 0.8,
        enable_limits: false,
        position_command_min: -1.0,
        position_command_max:  1.0,
        position_step_max: 0.2,
      }
      joint_6: {
        mode: "position",
        command_interface_names: ["effort", "position", "velocity"],
        state_interface_names: ["effort", "position", "velocity"],
        impedance_damping: 0.2,
        impedance_stiffness: 0.3,
        enable_limits: false,
        position_command_min: -1.0,
        position_command_max:  1.0,
        position_step_max: 0.2,
      }